'use client'
import Navbar from '../../components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import { SessionProvider } from "next-auth/react"
import { authOptions } from './api/auth/[...nextauth]/route'
const inter = Inter({ subsets: ['latin'] })

 const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <SessionProvider session={authOptions}>

        <Navbar/>
        {children}
        </SessionProvider>

        </body>
    </html>
  )
}
